use_default_settings: true

server:
  image_proxy: true
  secret_key: notasecretkey

search:
  formats:
    - html
    - json

engines:
  - name: bing
    disabled: false
  - name: brave
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: duckduckgo web
    disabled: false
  - name: google cse
    disabled: false
  - name: mojeek
    disabled: false
  - name: presearch
    disabled: false
  - name: qwant
    disabled: false
  - name: startpage
    disabled: false
  - name: wikipedia
    disabled: false
  - name: yahoo
    disabled: false
  - name: yandex
    disabled: false
  - name: yep
    disabled: false
